name: Pull-request CI

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: [macos-latest, ubuntu-latest]
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install nvidia cuda toolkit
      if: >
        matrix.operating-system == 'ubuntu-latest'
      run: >
        sudo apt install nvidia-cuda-toolkit

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2

    - run: poetry install --with dev

    - run: poetry run black --check .

    - run: poetry run mypy .

    - run: poetry run pytest --cov
